Added build directory

diff --git a/src/tools/BinaryAnalysis/Makefile.in b/src/tools/BinaryAnalysis/Makefile.in
--- a/src/tools/BinaryAnalysis/Makefile.in
+++ b/src/tools/BinaryAnalysis/Makefile.in
@@ -116,13 +116,22 @@ PRE_UNINSTALL = :
 POST_UNINSTALL = :
 build_triplet = @build@
 host_triplet = @host@
-@ROSE_USE_CLANG_FRONTEND_TRUE@am__append_1 = $(CLANG_LDFLAGS) -ltinfo
+
+# DQ (10/23/2020): Pei-Hung and I think this may not be required (not available on my system).
+# I get the error: 
+#    /bin/ld: skipping incompatible /lib/libtinfo.so when searching for -ltinfo
+#    clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
+# ROSE_LIBS += $(CLANG_LDFLAGS) -ltinfo
+@ROSE_USE_CLANG_FRONTEND_TRUE@am__append_1 = $(CLANG_LDFLAGS)
+@ROSE_EXPERIMENTAL_ADA_ROSE_CONNECTION_TRUE@am__append_2 = -R $(DOT_ASIS_LIB_DIR_) 
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bin_PROGRAMS =  \
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-ana$(EXEEXT) \
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-cc$(EXEEXT) \
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-cfg$(EXEEXT) \
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-container$(EXEEXT) \
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-dis$(EXEEXT) \
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-insnfreq$(EXEEXT) \
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-insnfreq-cmp$(EXEEXT) \
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-entropy$(EXEEXT) \
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-linear$(EXEEXT) \
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-lsb$(EXEEXT) \
@@ -334,10 +343,9 @@ am__DEPENDENCIES_8 = $(abspath $(top_builddir)/src/librose.la) \
 	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
 	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_6) \
 	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
-	$(am__DEPENDENCIES_1) $(ROSE_ADA_LIBS_WITH_PATH) \
 	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
 	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
-	$(am__DEPENDENCIES_7)
+	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_7)
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_ana_DEPENDENCIES =  \
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	libbatSupport.a \
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	$(am__DEPENDENCIES_8)
@@ -394,6 +402,25 @@ bat_entropy_OBJECTS = $(am_bat_entropy_OBJECTS)
 bat_entropy_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
 	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
 	$(CXXFLAGS) $(bat_entropy_LDFLAGS) $(LDFLAGS) -o $@
+am__bat_insnfreq_SOURCES_DIST = bat-insnfreq.C
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@am_bat_insnfreq_OBJECTS = bat_insnfreq-bat-insnfreq.$(OBJEXT)
+bat_insnfreq_OBJECTS = $(am_bat_insnfreq_OBJECTS)
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_insnfreq_DEPENDENCIES =  \
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	libbatSupport.a \
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	$(am__DEPENDENCIES_8)
+bat_insnfreq_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
+	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
+	$(CXXFLAGS) $(bat_insnfreq_LDFLAGS) $(LDFLAGS) -o $@
+am__bat_insnfreq_cmp_SOURCES_DIST = bat-insnfreq-cmp.C
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@am_bat_insnfreq_cmp_OBJECTS = bat_insnfreq_cmp-bat-insnfreq-cmp.$(OBJEXT)
+bat_insnfreq_cmp_OBJECTS = $(am_bat_insnfreq_cmp_OBJECTS)
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_insnfreq_cmp_DEPENDENCIES =  \
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	libbatSupport.a \
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	$(am__DEPENDENCIES_8)
+bat_insnfreq_cmp_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX \
+	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CXXLD) \
+	$(AM_CXXFLAGS) $(CXXFLAGS) $(bat_insnfreq_cmp_LDFLAGS) \
+	$(LDFLAGS) -o $@
 am__bat_linear_SOURCES_DIST = bat-linear.C
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@am_bat_linear_OBJECTS = bat_linear-bat-linear.$(OBJEXT)
 bat_linear_OBJECTS = $(am_bat_linear_OBJECTS)
@@ -493,6 +520,7 @@ am__v_CXXLD_1 =
 SOURCES = $(libbatSupport_a_SOURCES) $(bat_ana_SOURCES) \
 	$(bat_cc_SOURCES) $(bat_cfg_SOURCES) $(bat_container_SOURCES) \
 	$(bat_dis_SOURCES) $(bat_entropy_SOURCES) \
+	$(bat_insnfreq_SOURCES) $(bat_insnfreq_cmp_SOURCES) \
 	$(bat_linear_SOURCES) $(bat_lsb_SOURCES) $(bat_lsf_SOURCES) \
 	$(bat_mem_SOURCES) $(bat_prop_SOURCES) \
 	$(bat_stack_deltas_SOURCES) $(bat_trace_SOURCES)
@@ -500,6 +528,8 @@ DIST_SOURCES = $(am__libbatSupport_a_SOURCES_DIST) \
 	$(am__bat_ana_SOURCES_DIST) $(am__bat_cc_SOURCES_DIST) \
 	$(am__bat_cfg_SOURCES_DIST) $(am__bat_container_SOURCES_DIST) \
 	$(am__bat_dis_SOURCES_DIST) $(am__bat_entropy_SOURCES_DIST) \
+	$(am__bat_insnfreq_SOURCES_DIST) \
+	$(am__bat_insnfreq_cmp_SOURCES_DIST) \
 	$(am__bat_linear_SOURCES_DIST) $(am__bat_lsb_SOURCES_DIST) \
 	$(am__bat_lsf_SOURCES_DIST) $(am__bat_mem_SOURCES_DIST) \
 	$(am__bat_prop_SOURCES_DIST) \
@@ -1079,10 +1109,10 @@ EDG_LIBS = @EDG_LIBS@
 
 # DQ (11/4/2016): Adding support for use of Address Sanitizer (for where the ROSE Test Handler (RTH) is used.
 # Note the quotes and escapes that are required:
-ADDRESS_SANITIZER_OPTIONS = "ASAN_OPTIONS=symbolize=1:detect_leaks=0 ASAN_SYMBOLIZER_PATH=\`which llvm-symbolizer\`"
+ADDRESS_SANITIZER_OPTIONS = "ASAN_OPTIONS=halt_on_error=0:symbolize=1:detect_leaks=0 ASAN_SYMBOLIZER_PATH=\`which llvm-symbolizer\`"
 
 # DQ(11/4/2016): Need a version when not using the ROSE Test Handler (RTH):
-NON_RTH_ADDRESS_SANITIZER_OPTIONS = ASAN_OPTIONS=symbolize=1:detect_leaks=0 ASAN_SYMBOLIZER_PATH=`which llvm-symbolizer`
+NON_RTH_ADDRESS_SANITIZER_OPTIONS = ASAN_OPTIONS=halt_on_error=1:symbolize=1:detect_leaks=0 ASAN_SYMBOLIZER_PATH=`which llvm-symbolizer`
 @ROSE_HAVE_LIBELF_TRUE@ROSE_ELF_INCLUDES = @LIBELF_CPPFLAGS@
 @ROSE_HAVE_LIBELF_TRUE@ROSE_ELF_LIBS_WITH_PATH = @LIBELF_LDFLAGS@
 
@@ -1190,8 +1220,9 @@ NON_RTH_ADDRESS_SANITIZER_OPTIONS = ASAN_OPTIONS=symbolize=1:detect_leaks=0 ASAN
 # DQ (5/9/2017): Adding Ada library support.
 # ROSE_ADA_INCLUDES = -I$(ada_path)/include_xxx
 @ROSE_EXPERIMENTAL_ADA_ROSE_CONNECTION_TRUE@ROSE_ADA_INCLUDES = -I$(ada_path)/include_xxx
-@ROSE_EXPERIMENTAL_ADA_ROSE_CONNECTION_TRUE@ROSE_ADA_LIBS = -ldot_asis
-@ROSE_EXPERIMENTAL_ADA_ROSE_CONNECTION_TRUE@ROSE_ADA_LIBS_WITH_PATH = $(DOT_ASIS_LIB_DIR_)/libdot_asis.so
+@ROSE_EXPERIMENTAL_ADA_ROSE_CONNECTION_TRUE@DOT_ASIS_LIB_DIR_ = $(abs_top_builddir)/src/frontend/Experimental_Ada_ROSE_Connection/dot_asis/dot_asis_library/lib
+#  ROSE_ADA_LIBS = -ldot_asis
+#  ROSE_ADA_LIBS_WITH_PATH = $(DOT_ASIS_LIB_DIR_)/libdot_asis.so
 
 # RASMUSSEN (10/24/2017): Adding the GnuCOBOL parse-tree library support.
 @ROSE_EXPERIMENTAL_COBOL_ROSE_CONNECTION_TRUE@ROSE_COBOL_PT_LIBS_WITH_PATH = -L$(COBPT_LIBRARY_PATH) -lcob -lcobpt
@@ -1473,9 +1504,13 @@ ROSE_LIBS = $(abspath $(top_builddir)/src/librose.la) -lm \
 	$(ROSE_LIBMAGIC_LIBS_WITH_PATH) \
 	$(ROSE_READLINE_LIBS_WITH_PATH) $(ROSE_DLIB_LIBS_WITH_PATH) \
 	$(ROSE_GCRYPT_LIBS_WITH_PATH) $(ROSE_LIBPQXX_LIBS_WITH_PATH) \
-	$(ROSE_ADA_LIBS_WITH_PATH) $(ROSE_COBOL_PT_LIBS_WITH_PATH) \
-	$(ROSE_PYTHON_LIBS_WITH_PATH) $(ROSE_QUAD_FLOAT_MATH) \
-	$(ROSE_CAPSTONE_LIBS_WITH_PATH) $(am__append_1)
+	$(ROSE_COBOL_PT_LIBS_WITH_PATH) $(ROSE_PYTHON_LIBS_WITH_PATH) \
+	$(ROSE_QUAD_FLOAT_MATH) $(ROSE_CAPSTONE_LIBS_WITH_PATH) \
+	$(am__append_1)
+
+#if ROSE_EXPERIMENTAL_ADA_ROSE_CONNECTION
+#ROSE_LIBS += $(libroseAdalibraries) 
+#endif
 
 #========================================================================================================================
 # These are the "-R directory" switches that need to be passed to libtool running in link mode to make sure that ROSE
@@ -1510,27 +1545,16 @@ ROSE_LIBS = $(abspath $(top_builddir)/src/librose.la) -lm \
 # split the named environment variable into individual directory names.  If there's a ROSE configure option to specify
 # the library location, then DO NOT list an environment variable here--use the directory from configure instead (which
 # goes into ROSE_LIBS above).
-ROSE_RPATHS = \
-          $(patsubst -L%,-R %,                                                          \
-            $(filter-out -L/lib% -L/usr/lib% -L/usr/local/lib% -L/var/lib%,             \
-              $(filter -L%,                                                             \
-                $(ROSE_LIBS)                                                            \
-                $(subst :, , $(GNU_COMPILERS_LIBDIRS))                                  \
-                $(subst :, , $(LIBBZ2_LIBDIRS))                                         \
-                $(subst :, , $(LIBGRAPHICSMAGICK_LIBDIRS))                              \
-                $(subst :, , $(LIBJPEG_LIBDIRS))                                        \
-                $(subst :, , $(LIBLCMS_LIBDIRS))                                        \
-                $(subst :, , $(LIBLZMA_LIBDIRS))                                        \
-                $(subst :, , $(LIBPNG_LIBDIRS))                                         \
-                $(subst :, , $(LIBTIFF_LIBDIRS))                                        \
-                $(subst :, , $(PYTHON_LIBDIRS))                                         \
-                $(subst :, , $(SPOT_LIBDIRS))                                           \
-                $(subst :, , $(ZLIB_LIBDIRS))                                           \
-                $(subst :, , $(INTEL_COMPILER_RPATHS))                                  \
-              )                                                                         \
-            )                                                                           \
-          )
-
+ROSE_RPATHS = $(patsubst -L%,-R %, $(filter-out -L/lib% -L/usr/lib% \
+	-L/usr/local/lib% -L/var/lib%, $(filter -L%, $(ROSE_LIBS) \
+	$(subst :, , $(GNU_COMPILERS_LIBDIRS)) $(subst :, , \
+	$(LIBBZ2_LIBDIRS)) $(subst :, , $(LIBGRAPHICSMAGICK_LIBDIRS)) \
+	$(subst :, , $(LIBJPEG_LIBDIRS)) $(subst :, , \
+	$(LIBLCMS_LIBDIRS)) $(subst :, , $(LIBLZMA_LIBDIRS)) $(subst \
+	:, , $(LIBPNG_LIBDIRS)) $(subst :, , $(LIBTIFF_LIBDIRS)) \
+	$(subst :, , $(PYTHON_LIBDIRS)) $(subst :, , $(SPOT_LIBDIRS)) \
+	$(subst :, , $(ZLIB_LIBDIRS)) $(subst :, , \
+	$(INTEL_COMPILER_RPATHS)) ) ) ) $(am__append_2)
 @OS_MACOSX_FALSE@ROSE_LINK_RPATHS = $(addprefix -Wl$(comma)-rpath , $(filter-out -R , $(ROSE_RPATHS)))
 
 # Rasmussen (3/23/2018): Added ROSE_LINK_RPATHS to enable linking on Mac OSX with ROSE installation
@@ -1580,13 +1604,15 @@ RTH_STATS = $(top_srcdir)/scripts/rth_stats.pl
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-cfg.passed \
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-container.passed \
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-dis.passed \
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-insnfreq.passed \
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-insnfreq-cmp.passed \
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-entropy.passed \
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-linear.passed \
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-lsb.passed \
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-lsf.passed \
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-mem.passed \
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-prop.passed \
-@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-stack.passed \
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-stack-deltas.passed \
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	bat-trace.passed
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@lib_LIBRARIES = libbatSupport.a
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@libbatSupport_a_SOURCES = batSupport.C
@@ -1612,6 +1638,14 @@ RTH_STATS = $(top_srcdir)/scripts/rth_stats.pl
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_dis_CPPFLAGS = $(ROSE_INCLUDES)
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_dis_LDFLAGS = $(ROSE_RPATHS)
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_dis_LDADD = libbatSupport.a $(ROSE_LIBS)
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_insnfreq_SOURCES = bat-insnfreq.C
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_insnfreq_CPPFLAGS = $(ROSE_INCLUDES)
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_insnfreq_LDFLAGS = $(ROSE_RPATHS)
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_insnfreq_LDADD = libbatSupport.a $(ROSE_LIBS)
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_insnfreq_cmp_SOURCES = bat-insnfreq-cmp.C
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_insnfreq_cmp_CPPFLAGS = $(ROSE_INCLUDES)
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_insnfreq_cmp_LDFLAGS = $(ROSE_RPATHS)
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_insnfreq_cmp_LDADD = libbatSupport.a $(ROSE_LIBS)
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_entropy_SOURCES = bat-entropy.C
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_entropy_CPPFLAGS = $(ROSE_INCLUDES)
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_entropy_LDFLAGS = $(ROSE_RPATHS)
@@ -1644,6 +1678,7 @@ RTH_STATS = $(top_srcdir)/scripts/rth_stats.pl
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_trace_CPPFLAGS = $(ROSE_INCLUDES)
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_trace_LDFLAGS = $(ROSE_RPATHS)
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@bat_trace_LDADD = libbatSupport.a $(ROSE_LIBS)
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@MOSTLYCLEANFILES = $(tests)
 all: all-am
 
 .SUFFIXES:
@@ -1788,6 +1823,14 @@ bat-entropy$(EXEEXT): $(bat_entropy_OBJECTS) $(bat_entropy_DEPENDENCIES) $(EXTRA
 	@rm -f bat-entropy$(EXEEXT)
 	$(AM_V_CXXLD)$(bat_entropy_LINK) $(bat_entropy_OBJECTS) $(bat_entropy_LDADD) $(LIBS)
 
+bat-insnfreq$(EXEEXT): $(bat_insnfreq_OBJECTS) $(bat_insnfreq_DEPENDENCIES) $(EXTRA_bat_insnfreq_DEPENDENCIES) 
+	@rm -f bat-insnfreq$(EXEEXT)
+	$(AM_V_CXXLD)$(bat_insnfreq_LINK) $(bat_insnfreq_OBJECTS) $(bat_insnfreq_LDADD) $(LIBS)
+
+bat-insnfreq-cmp$(EXEEXT): $(bat_insnfreq_cmp_OBJECTS) $(bat_insnfreq_cmp_DEPENDENCIES) $(EXTRA_bat_insnfreq_cmp_DEPENDENCIES) 
+	@rm -f bat-insnfreq-cmp$(EXEEXT)
+	$(AM_V_CXXLD)$(bat_insnfreq_cmp_LINK) $(bat_insnfreq_cmp_OBJECTS) $(bat_insnfreq_cmp_LDADD) $(LIBS)
+
 bat-linear$(EXEEXT): $(bat_linear_OBJECTS) $(bat_linear_DEPENDENCIES) $(EXTRA_bat_linear_DEPENDENCIES) 
 	@rm -f bat-linear$(EXEEXT)
 	$(AM_V_CXXLD)$(bat_linear_LINK) $(bat_linear_OBJECTS) $(bat_linear_LDADD) $(LIBS)
@@ -1872,6 +1915,18 @@ bat_entropy-bat-entropy.o: bat-entropy.C
 
 bat_entropy-bat-entropy.obj: bat-entropy.C
 	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bat_entropy_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o bat_entropy-bat-entropy.obj `if test -f 'bat-entropy.C'; then $(CYGPATH_W) 'bat-entropy.C'; else $(CYGPATH_W) '$(srcdir)/bat-entropy.C'; fi`
+
+bat_insnfreq-bat-insnfreq.o: bat-insnfreq.C
+	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bat_insnfreq_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o bat_insnfreq-bat-insnfreq.o `test -f 'bat-insnfreq.C' || echo '$(srcdir)/'`bat-insnfreq.C
+
+bat_insnfreq-bat-insnfreq.obj: bat-insnfreq.C
+	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bat_insnfreq_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o bat_insnfreq-bat-insnfreq.obj `if test -f 'bat-insnfreq.C'; then $(CYGPATH_W) 'bat-insnfreq.C'; else $(CYGPATH_W) '$(srcdir)/bat-insnfreq.C'; fi`
+
+bat_insnfreq_cmp-bat-insnfreq-cmp.o: bat-insnfreq-cmp.C
+	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bat_insnfreq_cmp_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o bat_insnfreq_cmp-bat-insnfreq-cmp.o `test -f 'bat-insnfreq-cmp.C' || echo '$(srcdir)/'`bat-insnfreq-cmp.C
+
+bat_insnfreq_cmp-bat-insnfreq-cmp.obj: bat-insnfreq-cmp.C
+	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bat_insnfreq_cmp_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o bat_insnfreq_cmp-bat-insnfreq-cmp.obj `if test -f 'bat-insnfreq-cmp.C'; then $(CYGPATH_W) 'bat-insnfreq-cmp.C'; else $(CYGPATH_W) '$(srcdir)/bat-insnfreq-cmp.C'; fi`
 
 bat_linear-bat-linear.o: bat-linear.C
 	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bat_linear_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o bat_linear-bat-linear.o `test -f 'bat-linear.C' || echo '$(srcdir)/'`bat-linear.C
@@ -2027,7 +2082,9 @@ distdir-am: $(DISTFILES)
 	    || exit 1; \
 	  fi; \
 	done
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_FALSE@check-local:
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) check-local
 check: check-am
 all-am: Makefile $(PROGRAMS) $(LIBRARIES) $(HEADERS)
 installdirs:
@@ -2054,6 +2111,7 @@ install-strip:
 	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
 	fi
 mostlyclean-generic:
+	-test -z "$(MOSTLYCLEANFILES)" || rm -f $(MOSTLYCLEANFILES)
 
 clean-generic:
 
@@ -2134,9 +2192,9 @@ ps-am:
 uninstall-am: uninstall-binPROGRAMS uninstall-libLIBRARIES \
 	uninstall-pkgincludeHEADERS
 
-.MAKE: install-am install-strip
+.MAKE: check-am install-am install-strip
 
-.PHONY: CTAGS GTAGS TAGS all all-am check check-am clean \
+.PHONY: CTAGS GTAGS TAGS all all-am check check-am check-local clean \
 	clean-binPROGRAMS clean-generic clean-libLIBRARIES \
 	clean-libtool clean-local cscopelist-am ctags ctags-am \
 	distclean distclean-compile distclean-generic \
@@ -2163,7 +2221,6 @@ uninstall-am: uninstall-binPROGRAMS uninstall-libLIBRARIES \
 
 @ROSE_HAVE_LIBZ3_TRUE@  # The previous "Z3_*" variables should have been named "ROSE_Z3_*" following the pattern in the rest of this
 @ROSE_HAVE_LIBZ3_TRUE@  # makefile. I don't want to break code that uses the wrong names, so I'll just add the correct ones. [Matzke 2017-10-17]
-@ROSE_EXPERIMENTAL_ADA_ROSE_CONNECTION_TRUE@  DOT_ASIS_LIB_DIR_ ?= /home/quinlan1/ROSE/ADA/dot_asis/dot_asis_library/lib
 
 show-rpaths:
 	@echo "ROSE_LIBS = $(ROSE_LIBS)"
@@ -2181,10 +2238,12 @@ clean-local: clean-test-targets
 .PHONY: clean-test-targets
 
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@$(tests): %.passed: %
-@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	@$(RTH_RUN)						\
-@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@		TITLE="testing $* [$@]"				\
-@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@		CMD="$$(pwd)/$* --self-test"			\
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@	@$(RTH_RUN)							\
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@		TITLE="testing $* [$@]"					\
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@		CMD="$$(pwd)/$* --self-test --no-error-if-disabled"	\
 @ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@		$(top_srcdir)/scripts/test_exit_status $@
+
+@ROSE_BUILD_BINARY_ANALYSIS_SUPPORT_TRUE@check-local: $(tests) bat-insnfreq.passed bat-insnfreq-cmp.passed
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
